### Reference
- http://www.numpy.org/
- http://aikorea.org/cs231n/python-numpy-tutorial/

### Install
- pip3 install numpy

### Make
- array
- reshape
- index
- zeros
- ones
- eye
- like
- empty
- arange
- linespace, logspace
- rand, randn
- stack
- concatenate
- split
- sort

In [3]:
import numpy as np

##### array
- ndim : 행렬의 차원
- shape : 행렬의 모양

In [16]:
# 1차원 배열 (vector)
array = np.array([0,1,2,3,4,5])
print(type(array))
print(array)

<class 'numpy.ndarray'>
[0 1 2 3 4 5]


In [17]:
# 2차원 배열 (3*1 matrix)
array = np.array([[0],[1],[2]]) 
print(array)

[[0]
 [1]
 [2]]


In [18]:
# 2차원 배열 (2*3 matrix)
array = np.array([
    [0,1,2],
    [3,4,5]
]) 
print(array)
print(array.ndim, array.shape)

[[0 1 2]
 [3 4 5]]
2 (2, 3)


In [19]:
# 3차원 배열 (2*3*4 matrix)
array = np.array([
    [[0,1,2,3],
     [4,5,6,7],
     [8,9,10,11]],
    [[0,1,2,3],
     [4,5,100,7],
     [8,9,10,11]]
]) 
print(array)
print(array.ndim, array.shape) # 바깥에서 안으로 모양을 나타낸다고 생각하면 편함

[[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[  0   1   2   3]
  [  4   5 100   7]
  [  8   9  10  11]]]
3 (2, 3, 4)


##### reshape
- 행렬의 모양을 바꿀수 있다.

In [20]:
na = np.array([1,2,3,4,5,6,7,8])
na.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
rna = np.reshape(na,(4,2))
rna

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [22]:
rna = np.reshape(na,(2,10)) # shape size error
rna

ValueError: cannot reshape array of size 8 into shape (2,10)

In [23]:
# 전치행렬
rna.T
print(rna.T)
print(rna.T.shape)

[[1 3 5 7]
 [2 4 6 8]]
(2, 4)


##### index
- 행렬의 특정 위치 데이터 값 가져오기
- 행렬 자르기

In [24]:
array

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[  0,   1,   2,   3],
        [  4,   5, 100,   7],
        [  8,   9,  10,  11]]])

In [25]:
print(array[1][1][2])
print(array[1,1,2])

100
100


In [26]:
result = array[1:,1:,2:]
print(result)
print(result.ndim, result.shape)

[[[100   7]
  [ 10  11]]]
3 (1, 2, 2)


In [27]:
result[0] # dimention reduction

array([[100,   7],
       [ 10,  11]])

##### zeros
- 행렬을 만들고 안에 0으로 채워 넣는다.

In [28]:
# 1차원
z = np.zeros(5)
print(z)
print(z.ndim, z.shape)

[0. 0. 0. 0. 0.]
1 (5,)


In [29]:
# 2차원 (2*3)
z = np.zeros((2,3))
print(z)
print(z.ndim, z.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
2 (2, 3)


In [30]:
# 3차원 (2*3*4)
z = np.zeros([2,3,4])
print(z)
print(z.ndim, z.shape)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3 (2, 3, 4)


##### ones
- 행렬을 만들고 안에 1을 채워 넣는다.

In [31]:
# 3차원 (2*3*4)
o = np.ones([2,3,4]) # or o = np.ones((2,3,4)) # tubple is okay either
print(o)
print(o.ndim, o.shape)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3 (2, 3, 4)


##### eye
- 단위 행렬 데이터를 만든다.

In [32]:
# 단위행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### like
- 행렬 안에 있는 모든 데이터를 0이나 1로 바꿀수 있다.

In [33]:
z

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [34]:
ls = np.ones_like(z)
print(ls)
print(ls.ndim, ls.shape)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3 (2, 3, 4)


In [35]:
o

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [36]:
ls = np.zeros_like(o)
print(ls)
print(ls.ndim, ls.shape)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3 (2, 3, 4)


##### empty
- 빈행렬을 만든다.
- 실제로는 빈데이터가 아니라 더미 데이터가 들어간다

In [37]:
a = np.empty((5,5))
print(a)

[[6.93811887e-310 4.67359990e-310 2.33419537e-312 9.76118064e-313
  2.41907520e-312]
 [2.05833592e-312 8.48798317e-313 1.03977794e-312 1.06099790e-312
  1.08221785e-312]
 [1.10343781e-312 1.12465777e-312 1.14587773e-312 1.16709769e-312
  1.18831764e-312]
 [8.70018275e-313 2.33419537e-312 9.76118064e-313 2.14321575e-312
  2.20687562e-312]
 [2.37663529e-312 8.48798317e-313 9.33678148e-313 8.70018275e-313
  9.16526748e+242]]


##### arange
- range와 같다.
- 하지만 큰데이터에서 range 보다 속도가 빠르다

In [38]:
# range와 arange의 속도 비교
size = int(1E6) # E : exponential
%timeit for x in range(size): x ** 2
%timeit for x in np.arange(size): x ** 2

289 ms ± 20 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
246 ms ± 14.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [39]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [41]:
np.arange(2,10,3)

array([2, 5, 8])

In [42]:
np.arange(10,1,-2)

array([10,  8,  6,  4,  2])

##### linspace, logspace

In [43]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [44]:
# log10(x)=2, log10(x)=2.5, log10(x)=3
# 10**2, 10**2.5, 10**3
print(np.logspace(2, 4, 3))
print(np.logspace(2, 3, 3))

[  100.  1000. 10000.]
[ 100.          316.22776602 1000.        ]


In [45]:
10**2, 10**2.5, 10**3

(100, 316.22776601683796, 1000)

##### random
- seed
- rand (uniform)
- randn (gaussian)
- randint
- shuffle
- choice

In [46]:
np.random.seed(0)
rd = np.random.rand(10)   # uniform 으로 난수 발생  (균등분포)
rdn = np.random.randn(10) # gaussian 으로 난수 발생 (정규분포 - 0에 가까운수가 많이 나옴)
print(rd)
print(rdn)

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152]
[ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323  0.33367433
  1.49407907 -0.20515826  0.3130677  -0.85409574]


In [47]:
# e-01 -> (10**-1)
np.random.seed(1)
rd = np.random.rand(4)
rdn = np.random.randn(4)
print(rd)
print(rdn)

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01]
[-0.52817175 -1.07296862  0.86540763 -2.3015387 ]


In [48]:
r = np.random.rand(2,3,4)
print(r)

[[[0.41919451 0.6852195  0.20445225 0.87811744]
  [0.02738759 0.67046751 0.4173048  0.55868983]
  [0.14038694 0.19810149 0.80074457 0.96826158]]

 [[0.31342418 0.69232262 0.87638915 0.89460666]
  [0.08504421 0.03905478 0.16983042 0.8781425 ]
  [0.09834683 0.42110763 0.95788953 0.53316528]]]


In [49]:
r = np.random.randint(0,10,(3,3))
print(r)

[[4 8 1]
 [4 0 3]
 [9 2 0]]


In [50]:
r = np.random.randint(10, size=(3,4))
r

array([[4, 9, 2, 7],
       [7, 9, 8, 6],
       [9, 3, 7, 7]])

In [51]:
# shuffle로 데이터의 순서를 바꿀수 있다.
np.random.shuffle(r)
r

array([[9, 3, 7, 7],
       [4, 9, 2, 7],
       [7, 9, 8, 6]])

In [52]:
# p의 확률로 range(5)를 10개 추출
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])

array([3, 0, 3, 3, 2, 3, 3, 3, 3, 2])

In [53]:
# unique로 데이터의 유일한 값에 대한 리스트와 값의 갯수를 구할수 있다
index, count = np.unique(r, return_counts=True)
index, count

(array([2, 3, 4, 6, 7, 8, 9]), array([1, 1, 1, 1, 4, 1, 3]))

##### stack
- 행렬을 쌓는것과 같이 합치는 방법

In [54]:
na1 = np.arange(6)
na2 = np.arange(6,12)
print(na1, na1.shape)
print(na2, na2.shape)

[0 1 2 3 4 5] (6,)
[ 6  7  8  9 10 11] (6,)


In [55]:
na3 = np.stack((na1, na2))
print(na3, na3.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] (2, 6)


In [56]:
na3 = np.stack((na1, na2), axis=1)
print(na3, na3.shape)

[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]] (6, 2)


In [57]:
na1 = np.arange(6)
na2 = np.arange(6,12)
na1 = np.random.randint(10, size=(2,3))
na2 = np.random.randint(10, size=(2,3))
print(na1, na1.shape)
print(na2, na2.shape)

na3 = np.stack((na1, na2))
print(na3, na3.shape)

[[0 8 7]
 [7 1 1]] (2, 3)
[[3 0 8]
 [6 4 5]] (2, 3)
[[[0 8 7]
  [7 1 1]]

 [[3 0 8]
  [6 4 5]]] (2, 2, 3)


In [58]:
# practice 1
ls = []
for i in range(5):
    print(range(7), i, i+3)
    print(range(7)[i:i+3])
    print(list(range(7)[i:i+3]), end="\n\n")
    ls.append(range(7)[i:i+3])    
ls

range(0, 7) 0 3
range(0, 3)
[0, 1, 2]

range(0, 7) 1 4
range(1, 4)
[1, 2, 3]

range(0, 7) 2 5
range(2, 5)
[2, 3, 4]

range(0, 7) 3 6
range(3, 6)
[3, 4, 5]

range(0, 7) 4 7
range(4, 7)
[4, 5, 6]



[range(0, 3), range(1, 4), range(2, 5), range(3, 6), range(4, 7)]

In [59]:

# 수직으로 합치기
np.vstack(ls)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [60]:
# 수평으로 합치기. 하지만 리스트가 된다
np.hstack(ls)

array([0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 4, 5, 4, 5, 6])

In [61]:
# 수평으로 합치기
data = [list(range(7)[i:i+3]) for i in range(5) ] 
print(data)
np.stack(data, axis=-1)

[[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6]]


array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [62]:
# practice 2
np.arange(5)[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

##### concatenate (결합)
- 가로 결합은 열의 갯수가 같아야 한다.
- 세로 결합은 행의 갯수가 같아야 한다.

In [69]:
r1 = np.random.randint(10, size=(2,3))
print(r1)

[[1 9 8]
 [2 3 1]]


In [70]:
r2 = np.random.randint(10, size=(3,2))
print(r2)

[[2 7]
 [2 6]
 [0 9]]


In [71]:
r3 = np.random.randint(10, size=(3,3))
print(r3)

[[2 6 6]
 [2 7 7]
 [0 6 5]]


In [72]:
# 가로 결합
np.concatenate([r1, r3], axis=0)

array([[1, 9, 8],
       [2, 3, 1],
       [2, 6, 6],
       [2, 7, 7],
       [0, 6, 5]])

In [73]:
# 세로 결합
np.concatenate([r2, r3], axis=1)

array([[2, 7, 2, 6, 6],
       [2, 6, 2, 7, 7],
       [0, 9, 0, 6, 5]])

##### split

In [106]:
r = np.arange(3,11)
r

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
r1 = np.split(r, [5]) # 앞에서 5번째를 기준으로 나눈다
r1

[array([3, 4, 5, 6, 7]), array([ 8,  9, 10])]

In [108]:
# r1에는 나눈 데이터의 첫번째 데이터가 r2에는 나눈 데이터의 두번째 데이터가 들어간다
r1, r2 = np.split(r, [5]) 
r1, r2

(array([3, 4, 5, 6, 7]), array([ 8,  9, 10]))

In [109]:
r1, r2, r3, r4, r5 = np.split(r, [2,4,6,8]) # 2,4,6,8을 기준으로 나눠 5개의 array 데이터가 생성된다.
r1, r2, r3, r4, r5

(array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([ 9, 10]),
 array([], dtype=int64))

##### vsplit/hsplit
- 행렬을 수직, 수평으로 나눈다

In [112]:
r = np.random.randint(10, size=(4,6))
r

array([[2, 6, 0, 5, 2, 1],
       [8, 5, 9, 4, 9, 1],
       [2, 0, 4, 7, 0, 6],
       [2, 4, 3, 6, 7, 6]])

In [74]:
# 수평으로 2개씩 자름
r1, r2 = np.vsplit(r, [2])
print(r1)
print()
print(r2)

[[9 3 7 7]
 [4 9 2 7]]

[[7 9 8 6]]


In [75]:
# 수직으로 3개씩 자름
r1, r2 = np.hsplit(r, [3])
print(r1)
print()
print(r2)

[[9 3 7]
 [4 9 2]
 [7 9 8]]

[[7]
 [7]
 [6]]


In [76]:
# 수직으로 2개씩 자름
r1, r2, r3 = np.hsplit(r, [2,4])
print(r1)
print()
print(r2)
print()
print(r3)

[[9 3]
 [4 9]
 [7 9]]

[[7 7]
 [2 7]
 [8 6]]

[]


##### sort

In [117]:
r1 = np.random.randint(10, size=(3,3))
print(r1)

[[3 0 6]
 [4 7 6]
 [2 9 5]]


In [118]:
# 가로로 sorting
r1.sort() # axis -1과 1은 같은 동작을 한다
r1

array([[0, 3, 6],
       [4, 6, 7],
       [2, 5, 9]])

In [119]:
# 세로로 sorting
r1.sort(axis=0) 
r1

array([[0, 3, 6],
       [2, 5, 7],
       [4, 6, 9]])

In [65]:
# 문제
# 1~9까지의 숫자가 들어가는 3*3 행렬을 만드세요
# 만든 행렬을 무작위로 섞으세요

In [120]:
result = np.arange(1, 10)
result

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
result = np.reshape(result, (3,3))
result

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [122]:
result.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [128]:
np.random.shuffule(reuslt)
result

AttributeError: module 'numpy.random' has no attribute 'shuffule'

In [129]:
np.c_[np.array[1,2,3], np.array[4,5,6]]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [130]:
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])