In [5]:
import numpy as np

In [6]:
data1 = np.array([80,85,100,90,95])
data2 = np.array([70,80,100,95,95])

##### 분산(variance)
- 1개의 이산정도를 나타냄
- 편차제곱의 평균

$ variance = \frac{\sum_{i=1}^n{(x_i-\bar{x})^2}}{n}, (\bar{x}:평균) $

In [2]:
# 분산
def variance(data):
    avg = np.average(data)
    var = 0
    for num in data:
        var += (num-avg) ** 2
    return var/len(data)

# test code (분산, 표준편차)
variance(data1), variance(data2), variance(data1)**0.5, variance(data2)**0.5

(50.0, 126.0, 7.0710678118654755, 11.224972160321824)

In [3]:
# numpy 분산
np.var(data1), np.var(data2), np.std(data1), np.std(data2)

(50.0, 126.0, 7.0710678118654755, 11.224972160321824)

##### 공분산(covariance)
- 2개의 확률변수의 상관정도를 나타냄
- 평균 편차곱
- 방향성은 보여줄수 있으나 강도를 나타내는데 한계가 있음 (표본데이터의 크기에 따라서 값이 많이 달라짐)

$ covariance = \frac{\sum_{i=1}^{n}{(x_i-\bar{x})(y_i-\bar{y})}}{n}, (\bar{x}:x의 평균, \bar{y}:y의 평균) $

In [4]:
def covariance(data1, data2):
    x_ = np.average(data1)
    y_ = np.average(data2)

    cov = 0
    for idx in range(len(data1)):
        cov += (data1[idx]-x_) * (data2[idx]-y_)

    return cov/(len(data1)-1) # 표본상관계수를 사용 (모상관계수를 사용하면 -1을 제거)

In [5]:
# teat code 1
data1 = np.array([80,85,100,90,95])
data2 = np.array([70,80,100,95,95])
result = covariance(data1, data2)
print(result)

93.75


In [6]:
# teat code 2
data3 = np.array([80,85,100,90,95])
data4 = np.array([100,90,70,90,80])
result = covariance(data3, data4)
print(result)

-87.5


In [7]:
np.cov(data1,data2) 

array([[ 62.5 ,  93.75],
       [ 93.75, 157.5 ]])

In [8]:
np.cov(data3,data4)
array([[ 62.5, -87.5],
       [-87.5, 130. ]])


array([[ 62.5, -87.5],
       [-87.5, 130. ]])

##### 상관계수(correlation coefficient)
- 공분산의 한계를 극복하기 위해서 만들어짐
- -1 ~ 1까지의 수를 가지며 0과 가까울수록 상관도가 적음을 의미
- x의 분산과 y의 분산을 곱한 결과의 제곱근을 나눠주면 x나 y의 변화량이 클수록 0에 가까워짐
- https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.corrcoef.html

$ correlation-coefficient = \frac{공분산}{\sqrt{{x분산} \cdot {y분산}}} $

최종 상관계수

$ r = \frac{\sum(x-\bar{x})(y-\bar{y})}{\sqrt{{\sum(x-\bar{x})^2}\cdot{\sum(y-\bar{y})^2}}} $

In [30]:
def cc1(data1, data2):
    
    x_ = np.average(data1)
    y_ = np.average(data2)

    lo_upper = 0
    lo_lower_data1 = 0
    lo_lower_data2 = 0
    
    for idx in range(len(data1)):
        lo_upper += (data1[idx]-x_) * (data2[idx]-y_)
        lo_lower_data1 += ((data1[idx]-x_) ** 2) 
        lo_lower_data2 += ((data2[idx]-y_) ** 2)

    return lo_upper/ ((lo_lower_data1 * lo_lower_data2) ** 0.5)

In [31]:
data1 = np.array([80,85,100,90,95])
data2 = np.array([70,80,100,95,95])
print(cc1(data1, data2))
np.corrcoef(data1, data2)

0.944911182523068


array([[1.        , 0.94491118],
       [0.94491118, 1.        ]])

In [9]:
def cc(data1, data2):
    
    x_ = np.average(data1)
    y_ = np.average(data2)
    
    cov, xv, yv = 0, 0, 0

    for idx in range(len(data1)):
        cov += (data1[idx] - x_) * (data2[idx] - y_)
        xv += (data1[idx] - x_) ** 2
        yv += (data2[idx] - y_) ** 2    
    return cov/((xv*yv)**0.5)

In [10]:
# teat code 1
data1 = np.array([80,85,100,90,95])
data2 = np.array([70,80,100,95,95])
print(cc(data1, data2))
np.corrcoef(data1, data2)

0.944911182523068


array([[1.        , 0.94491118],
       [0.94491118, 1.        ]])

In [11]:
# teat code 2
data3 = np.array([80,85,100,90,95])
data4 = np.array([100,90,70,90,80])
print(cc(data3, data4))
np.corrcoef(data3, data4)

-0.970725343394151


array([[ 1.        , -0.97072534],
       [-0.97072534,  1.        ]])

In [12]:
# teat code 3
data5 = np.array([80,85,100,90,95])
data6 = np.array([90,95,100,80,85])
print(cc(data5, data6))
np.corrcoef(data5, data6)

0.2


array([[1. , 0.2],
       [0.2, 1. ]])

##### 결정계수(cofficient of determination)
- x로부터 y를 예측할수 있는 정도
- 상관계수의 제곱 (상관계수를 양수화)
- 수치가 클수록 예측할수 있는 정도가 더 정확

##### 프리미어리그 데이터에서 승점에 득점과 실점중에 어떤게 더 영향을 미칠까?

In [32]:
# 승점
point = np.array([81,65,63,61,56,48,43,40,40,36,36,34,32,31,31,30,30,28,27,20])

# 득점
gf = np.array([85,58,73,59,52,55,27,45,37,37,39,28,30,25,25,30,36,29,29,24])

# 실점
ga = np.array([20,23,34,25,27,41,26,43,50,49,55,40,40,42,52,48,57,44,58,49])

In [33]:
cc1(point, gf), cc1(point, ga)

(0.9364548116039453, -0.8231510970282541)

In [14]:
# 득점과 승점
result1 = cc(point, gf)

# 실점과 승점
result2 = cc(point, ga)

result1, result2

(0.9364548116039453, -0.8231510970282541)

In [15]:
# 실점보다 득점이 승점에 더 영향을 많이 끼침