### Quiz

In [39]:
import numpy as np

##### 1. 5개의 1로 이루어진 정수데이터 타입의 벡터를 만드세요

In [2]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

##### 2. 10개의 1로 이루어진 정수 데이터 타입의 벡터에서 마지막 3개의 데이터는 5가 들어있는 벡터를 만드세요

In [40]:
data = np.ones(10, dtype=int)
data[-3:] = 5
data

array([1, 1, 1, 1, 1, 1, 1, 5, 5, 5])

##### 3. 10에서 20까지의 데이터를 가지는 벡터를 만드세요

In [42]:
np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

##### 4. 위 벡터의 순서를 바꾸세요

In [43]:
_[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

##### 5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요

In [44]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### 6. 위의 벡터에서  `[[4,5],[7,8]]`  행렬을 만드세요

In [45]:
_[1:,1:]

array([[4, 5],
       [7, 8]])

##### 7. 1에서 10까지의 데이터를 랜덤하게 가지는 3*4 행렬을 만드세요

In [46]:
np.random.randint(1,11, (3,4))

array([[ 3,  7,  1,  4],
       [ 1,  9,  4,  8],
       [ 1,  8,  1, 10]])

##### 8. 위에서 만든 행렬의 unique 한 숫자들 리스트와 각숫자의 갯수를 리스트로 나타내세요

In [47]:
np.unique(_, return_counts=True)

(array([ 1,  3,  4,  7,  8,  9, 10]), array([4, 1, 2, 1, 2, 1, 1]))

##### 9. 1에서 12까지에 숫자가 들어간 3*4 행렬을 만드시고 행과 열에 관계없이 데이터를 섞으세요

In [48]:
data = np.arange(1,13).reshape(3,4)
data

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
data = data.reshape(12)
np.random.shuffle(data)
data.reshape(3,4)

array([[ 5,  7,  3,  2],
       [ 8, 11,  9,  1],
       [ 4, 10,  6, 12]])

##### 10. 1부터 10까지의 랜덤한 데이터가 들어가는 `3*3`행렬을 만드시고 가장 아래에 위의 데이터를 모두 합한 `1*3`행렬을 추가해서 `4*3`행렬을 만드세요

In [53]:
data = np.random.randint(1,11, size=(3,3))
data

array([[ 7,  4,  5],
       [ 1,  7,  1],
       [ 3,  2, 10]])

In [56]:
sum_data = np.sum(data, axis=0).reshape(1,3)
np.concatenate( [data, sum_data] )

array([[ 7,  4,  5],
       [ 1,  7,  1],
       [ 3,  2, 10],
       [11, 13, 16]])

##### 11. 10번문제의 결과로 나온 행렬데이터에서 평균값을 출력하고 평균값보다 큰 숫자들만 유니크한 리스트로 나열하세요 (평균값은 소수 둘째 자리까지만 나타내세요)

In [57]:
data = _

In [60]:
avg_data = data.mean()
data = data[data > avg_data]
print("avg : ", round(avg_data, 2))
np.unique(data)

avg :  6.67


array([ 7, 10, 11, 13, 16])

##### 12. 1부터 20까지의 랜덤숫자를 가지는 5*5 행렬을 만드시고 최대값에는 숫자(MAX), 최소값에는 숫자(MIN)으로 행렬을 바꾸세요

In [67]:
data = np.random.randint(1,21, size=(5,5))
data

array([[20,  3,  5, 17,  5],
       [ 2,  2,  6, 14, 16],
       [10, 19, 20,  7,  9],
       [13, 15,  2, 14,  4],
       [ 2, 10, 14, 17, 15]])

In [68]:
min_number, max_number = np.min(data), np.max(data)
min_number, max_number

(2, 20)

In [71]:
min_number, max_number = np.min(data), np.max(data)
min_idx = data == min_number
max_idx = data == max_number

In [73]:
data = data.astype("str")
data[min_idx] = str(min_number) + "(MIN)"
data[max_idx] = str(max_number) + "(MAX)"
data

array([['20(MAX)', '3', '5', '17', '5'],
       ['2(MIN)', '2(MIN)', '6', '14', '16'],
       ['10', '19', '20(MAX)', '7', '9'],
       ['13', '15', '2(MIN)', '14', '4'],
       ['2(MIN)', '10', '14', '17', '15']], dtype='<U21')

##### 13. 100에서 120까지의 랜덤 숫자를 가지는 8*8행렬을 만드시고 3의 배수에는 fiz, 5의 배수에는 buz, 3과 5의 배수는 fbz 문자를 출력하세요

In [74]:
data = np.random.randint(100, 121, size=(8,8))
data

array([[107, 120, 115, 118, 120, 115, 102, 117],
       [101, 111, 108, 101, 114, 116, 112, 113],
       [110, 115, 108, 109, 100, 105, 100, 101],
       [107, 108, 105, 111, 117, 120, 109, 117],
       [107, 106, 105, 106, 105, 101, 117, 119],
       [110, 120, 107, 118, 118, 118, 118, 101],
       [100, 112, 115, 104, 109, 113, 119, 104],
       [114, 105, 112, 115, 107, 100, 101, 110]])

In [75]:
idx_3 = data % 3 == 0 
idx_5 = data % 5 == 0
idx_15 = data % 15 == 0

In [77]:
data = data.astype("str")
data[idx_3] = "fiz"
data[idx_5] = "buz"
data[idx_15] = "fbz"
data

array([['107', 'fbz', 'buz', '118', 'fbz', 'buz', 'fiz', 'fiz'],
       ['101', 'fiz', 'fiz', '101', 'fiz', '116', '112', '113'],
       ['buz', 'buz', 'fiz', '109', 'buz', 'fbz', 'buz', '101'],
       ['107', 'fiz', 'fbz', 'fiz', 'fiz', 'fbz', '109', 'fiz'],
       ['107', '106', 'fbz', '106', 'fbz', '101', 'fiz', '119'],
       ['buz', 'fbz', '107', '118', '118', '118', '118', '101'],
       ['buz', '112', 'buz', '104', '109', '113', '119', '104'],
       ['fiz', 'fbz', '112', 'buz', '107', 'buz', '101', 'buz']],
      dtype='<U21')

##### 14. 리스트 컴프리헨션을 이용하여 아래와 같은 규칙은 갖는 행렬을 만드세요

In [78]:
number = 5
data = np.array([[ i*j for j in range(1, number + 1)] for i in range(1, number + 1)])
print("number : ", number)
data

number :  5


array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [79]:
number = 7
data = np.array([[ i*j for j in range(1, number + 1)] for i in range(1, number + 1)])
print("number : ", number)
data

number :  7


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 2,  4,  6,  8, 10, 12, 14],
       [ 3,  6,  9, 12, 15, 18, 21],
       [ 4,  8, 12, 16, 20, 24, 28],
       [ 5, 10, 15, 20, 25, 30, 35],
       [ 6, 12, 18, 24, 30, 36, 42],
       [ 7, 14, 21, 28, 35, 42, 49]])