### Datatype
- boolean : bool
- integer : int64
- float : float64
- byte String : S24
- unicode String : U24

In [1]:
import numpy as np

In [2]:
na = np.array([True, False])
na.dtype

dtype('bool')

In [3]:
na = np.array([1, 2, 3])
na.dtype

dtype('int64')

In [4]:
na = np.array([1.0, 2.0, 3.0])
na.dtype

dtype('float64')

##### change datatype

In [5]:
na = np.array([-1.0, 0.0, 1.0, 2.2, 3.8])
print(na)

na = na.astype('int64')
print(na)

na = na.astype('bool')
print(na)

na = na.astype('S24')
print(na)

na = na.astype('U24')
print(na)

[-1.   0.   1.   2.2  3.8]
[-1  0  1  2  3]
[ True False  True  True  True]
[b'True' b'False' b'True' b'True' b'True']
['True' 'False' 'True' 'True' 'True']


In [7]:
# 5~10까지 랜덤한 숫자가 들어있는 5*5 행렬
na = np.random.rand(5,5)
print(na)
print()
na = (na*6+5).astype('int64')
print(na)

[[0.55126503 0.51328249 0.52195226 0.17518021 0.24045939]
 [0.44481774 0.64727086 0.0025231  0.65953094 0.35409431]
 [0.22216299 0.8033385  0.5662761  0.00476899 0.53996584]
 [0.08990669 0.22755813 0.65385421 0.04728654 0.38490652]
 [0.63870687 0.54412726 0.79641993 0.17928296 0.5349221 ]]

[[8 8 8 6 6]
 [7 8 5 8 7]
 [6 9 8 5 8]
 [5 6 8 5 7]
 [8 8 9 6 8]]
