### Reference
- http://www.numpy.org/
- http://aikorea.org/cs231n/python-numpy-tutorial/

### Install
- pip3 install numpy

### Make
- array
- reshape
- index
- zeros
- ones
- eye
- like
- empty
- arange
- linespace, logspace
- rand, randn
- stack
- concatenate
- split
- sort

In [2]:
import numpy as np

##### array
- ndim : 행렬의 차원
- shape : 행렬의 모양

In [ ]:
# 1차원 배열 (vector)
array = np.array([0,1,2,3,4,5])
print(type(array))
print(array)

In [ ]:
# 2차원 배열 (1*3 matrix)
array = np.array([[0],[1],[2]]) 
print(array)

In [ ]:
# 2차원 배열 (2*3 matrix)
array = np.array([
    [0,1,2],
    [3,4,5]
]) 
print(array)

In [3]:
# 3차원 배열 (2*3*4 matrix)
array = np.array([
    [[0,1,2,3],
     [4,5,6,7],
     [8,9,10,11]],
    [[0,1,2,3],
     [4,5,100,7],
     [8,9,10,11]]
]) 
print(array)
print(array.ndim, array.shape) # 바깥에서 안으로 모양을 나타낸다고 생각하면 편함

[[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[  0   1   2   3]
  [  4   5 100   7]
  [  8   9  10  11]]]
3 (2, 3, 4)


##### reshape
- 행렬의 모양을 바꿀수 있다.

In [4]:
na = np.array([1,2,3,4,5,6,7,8])
na.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
rna = np.reshape(na,(4,2))
rna

In [ ]:
# 전치행렬
rna.T

##### index
- 행렬의 특정 위치 데이터 값 가져오기
- 행렬 자르기

In [ ]:
array

In [ ]:
print(array[1][1][2])
print(array[1,1,2])

In [ ]:
result = array[1:,1:,2:]
print(result)
print(result.ndim, result.shape)

##### zeros
- 행렬을 만들고 안에 0으로 채워 넣는다.

In [ ]:
# 1차원
z = np.zeros(5)
print(z)
print(z.ndim, z.shape)

In [ ]:
# 2차원 (2*3)
z = np.zeros((2,3))
print(z)
print(z.ndim, z.shape)

In [ ]:
# 3차원 (2*3*4)
z = np.zeros([2,3,4])
print(z)
print(z.ndim, z.shape)

##### ones
- 행렬을 만들고 안에 1을 채워 넣는다.

In [ ]:
# 3차원 (2*3*4)
o = np.ones([2,3,4])
print(o)
print(o.ndim, o.shape)

##### eye
- 단위 행렬 데이터를 만든다.

In [ ]:
# 단위행렬
np.eye(3)

##### like
- 행렬 안에 있는 모든 데이터를 0이나 1로 바꿀수 있다.

In [ ]:
z

In [ ]:
ls = np.ones_like(z)
print(ls)
print(ls.ndim, ls.shape)

In [ ]:
o

In [ ]:
ls = np.zeros_like(o)
print(ls)
print(ls.ndim, ls.shape)

##### empty
- 빈행렬을 만든다.
- 실제로는 빈데이터가 아니라 더미 데이터가 들어간다

In [ ]:
a = np.empty((5,5))
print(a)

##### arange
- range와 같다.
- 하지만 큰데이터에서 range 보다 속도가 빠르다

In [ ]:
# range와 arange의 속도 비교
size = int(1E6) # E : exponential
%timeit for x in range(size): x ** 2
%timeit for x in np.arange(size): x ** 2

In [ ]:
np.arange(10)

In [ ]:
np.arange(5,10)

In [ ]:
np.arange(2,10,3)

In [ ]:
np.arange(10,1,-2)

##### linspace, logspace

In [ ]:
np.linspace(0, 100, 5)

In [ ]:
# log10(x)=2, log10(x)=2.5, log10(x)=3
# 10**2, 10**2.5, 10**3
print(np.logspace(2, 4, 3))
print(np.logspace(2, 3, 3))

In [ ]:
10**2, 10**2.5, 10**3

##### random
- seed
- rand (uniform)
- randn (gaussian)
- randint
- shuffle
- choice

In [ ]:
np.random.seed(0)
rd = np.random.rand(10)   # uniform 으로 난수 발생  (균등분포)
rdn = np.random.randn(10) # gaussian 으로 난수 발생 (정규분포 - 0에 가까운수가 많이 나옴)
print(rd)
print(rdn)

In [ ]:
# e-01 -> (10**-1)
np.random.seed(1)
rd = np.random.rand(4)
rdn = np.random.randn(4)
print(rd)
print(rdn)

In [ ]:
r = np.random.rand(2,3,4)
print(r)

In [ ]:
r = np.random.randint(0,10,(3,3))
print(r)

In [ ]:
r = np.random.randint(10, size=(3,4))
r

In [ ]:
# shuffle로 데이터의 순서를 바꿀수 있다.
np.random.shuffle(r)
r

In [ ]:
# p의 확률로 range(5)를 10개 추출
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])

In [ ]:
# unique로 데이터의 유일한 값에 대한 리스트와 값의 갯수를 구할수 있다
index, count = np.unique(r, return_counts=True)
index, count

##### stack
- 행렬을 쌓는것과 같이 합치는 방법

In [ ]:
na1 = np.arange(6)
na2 = np.arange(6,12)
print(na1, na1.shape)
print(na2, na2.shape)

In [ ]:
na3 = np.stack((na1, na2))
print(na3, na3.shape)

In [ ]:
na3 = np.stack((na1, na2), axis=1)
print(na3, na3.shape)

In [ ]:
# practice 1
ls = []
for i in range(5):
    print(range(7), i, i+3)
    print(range(7)[i:i+3])
    print(list(range(7)[i:i+3]), end="\n\n")
    ls.append(range(7)[i:i+3])    
ls

In [ ]:
# 수직으로 합치기
np.vstack(ls)

In [ ]:
# 수평으로 합치기. 하지만 리스트가 된다
np.hstack(ls)

In [ ]:
# 수평으로 합치기
data = [list(range(7)[i:i+3]) for i in range(5) ] 
print(data)
np.stack(data, axis=-1)

In [ ]:
# practice 2
np.arange(5)[:, np.newaxis]

##### concatenate (결합)
- 가로 결합은 열의 갯수가 같아야 한다.
- 세로 결합은 행의 갯수가 같아야 한다.

In [ ]:
r1 = np.random.randint(10, size=(2,3))
print(r1)

In [ ]:
r2 = np.random.randint(10, size=(3,2))
print(r2)

In [ ]:
r3 = np.random.randint(10, size=(3,3))
print(r3)

In [ ]:
# 가로 결합
np.concatenate([r1, r3], axis=0)

In [ ]:
# 세로 결합
np.concatenate([r2, r3], axis=1)

##### split

In [ ]:
r = np.arange(5,20)
r

In [ ]:
r1 = np.split(r, [5]) # 앞에서 5번째를 기준으로 나눈다
r1

In [ ]:
# r1에는 나눈 데이터의 첫번째 데이터가 r2에는 나눈 데이터의 두번째 데이터가 들어간다
r1, r2 = np.split(r, [5]) 
r1, r2

In [ ]:
r1, r2, r3, r4, r5 = np.split(r, [2,4,6,8]) # 2,4,6,8을 기준으로 나눠 5개의 array 데이터가 생성된다.
r1, r2, r3, r4, r5

##### vsplit/hsplit
- 행렬을 수직, 수평으로 나눈다

In [ ]:
r = np.random.randint(10, size=(4,6))
r

In [ ]:
# 수평으로 2개씩 자름
r1, r2 = np.vsplit(r, [2])
print(r1)
print(r2)

In [ ]:
# 수직으로 3개씩 자름
r1, r2 = np.hsplit(r, [3])
print(r1)
print(r2)

In [ ]:
# 수직으로 2개씩 자름
r1, r2, r3 = np.hsplit(r, [2,4])
print(r1)
print(r2)
print(r3)

##### sort

In [ ]:
r1 = np.random.randint(10, size=(3,3))
print(r1)

In [ ]:
# 가로로 sorting
r1.sort() # axis -1과 1은 같은 동작을 한다
r1

In [ ]:
# 세로로 sorting
r1.sort(axis=0) 
r1

In [ ]:
# 문제
# 1~9까지의 숫자가 들어가는 3*3 행렬을 만드세요
# 만든 행렬을 무작위로 섞으세요