### Datatype
- boolean : bool
- integer : int64
- float : float64
- byte String : S24
- unicode String : U24

In [1]:
import numpy as np

In [2]:
na = np.array([True, False])
na.dtype

dtype('bool')

In [3]:
na = np.array([1, 2, 3])
na.dtype

dtype('int64')

In [4]:
na = np.array([1.0, 2.0, 3.0])
na.dtype

dtype('float64')

##### change datatype

In [5]:
na = np.array([-1.0, 0.0, 1.0, 2.2, 3.8])
print(na)

na = na.astype('int64')
print(na)

na = na.astype('bool')
print(na)

na = na.astype('S24')
print(na)

na = na.astype('U24')
print(na)

[-1.   0.   1.   2.2  3.8]
[-1  0  1  2  3]
[ True False  True  True  True]
[b'True' b'False' b'True' b'True' b'True']
['True' 'False' 'True' 'True' 'True']


In [6]:
# 5~10까지 랜덤한 숫자가 들어있는 5*5 행렬
na = np.random.rand(5,5)
print(na)

na = (na*6+5).astype('int64')
print(na)

[[0.36064592 0.54186083 0.31971931 0.634231   0.19663242]
 [0.80624585 0.30158724 0.95053635 0.31164679 0.50381161]
 [0.1766862  0.72671616 0.27101525 0.34389469 0.02710435]
 [0.66749351 0.44612516 0.12697746 0.43445204 0.57836258]
 [0.42230055 0.19610993 0.09313154 0.99250573 0.57018458]]
[[ 7  8  6  8  6]
 [ 9  6 10  6  8]
 [ 6  9  6  7  5]
 [ 9  7  5  7  8]
 [ 7  6  5 10  8]]
