### Quiz

In [2]:
import numpy as np

##### 1. 5개의 1로 이루어진 정수데이터 타입의 벡터를 만드세요 - ok

In [2]:
# data = np.array([1,1,1,1,1], dtype = int)
# data

#or

data1 = np.ones(5, dtype = int)
data1

array([1, 1, 1, 1, 1])

##### 2. 10개의 1로 이루어진 정수 데이터 타입의 벡터에서 마지막 3개의 데이터는 5가 들어있는 벡터를 만드세요 -ok

In [3]:
data = np.ones(10, dtype = int)
data[7:] = 5
print(data)


[1 1 1 1 1 1 1 5 5 5]


##### 3. 10에서 20까지의 데이터를 가지는 벡터를 만드세요 - ok

In [4]:
data = np.arange(10, 21)
data

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

##### 4. 위 벡터의 순서를 바꾸세요 - ok

In [5]:
data = np.arange(10, 21)[::-1]
data

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

##### 5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요 - ok

In [6]:
data = np.arange(0, 9).reshape(3,3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### 6. 위의 벡터에서  `[[4,5],[7,8]]`  행렬을 만드세요 - okay

In [131]:
data = np.arange(0, 9).reshape(3,3)
data1 = data[1:,1:]
print(data1)

[[4 5]
 [7 8]]


##### 7. 1에서 10까지의 데이터를 랜덤하게 가지는 3*4 행렬을 만드세요 - ok

In [8]:
np.random.seed(1) #fixed random number generate 
data = np.random.randint(1,11,(3,4))
data

array([[ 6,  9, 10,  6],
       [ 1,  1,  2,  8],
       [ 7, 10,  3,  5]])

##### 8. 위에서 만든 행렬의 unique 한 숫자들 리스트와 각숫자의 갯수를 리스트로 나타내세요 - ok

In [9]:
index, count = np.unique(data, return_counts=True)
index, count

(array([ 1,  2,  3,  5,  6,  7,  8,  9, 10]),
 array([2, 1, 1, 1, 2, 1, 1, 1, 2]))

##### 9. 1에서 12까지에 숫자가 들어간 3*4 행렬을 만드시고 행과 열에 관계없이 데이터를 섞으세요 - ok

In [10]:
np.random.seed(1) #fixed random number generate 
data = np.random.randint(1,13,(3,4))
print("random 3x4 matrix\n", data)
print()
np.random.shuffle(data)
print("shuffled 3x4 matrix\n",data)

random 3x4 matrix
 [[ 6 12  9 10]
 [12  6  1  1]
 [ 2  8  7 10]]

shuffled 3x4 matrix
 [[12  6  1  1]
 [ 6 12  9 10]
 [ 2  8  7 10]]


##### 10. 1부터 10까지의 랜덤한 데이터가 들어가는 `3*3`행렬을 만드시고 가장 아래에 위의 데이터를 모두 합한 `1*3`행렬을 추가해서 `4*3`행렬을 만드세요 - ok

In [11]:
np.random.seed(1) #fixed random number generate 
data = np.random.randint(1,11,(3,3))
print(data)
print()
data1 = data[0]  +  data[1] + data[2]   
print(data1)
print()
data2 = np.vstack((data, data1))
print(data2)


[[ 6  9 10]
 [ 6  1  1]
 [ 2  8  7]]

[14 18 18]

[[ 6  9 10]
 [ 6  1  1]
 [ 2  8  7]
 [14 18 18]]


##### 11. 10번문제의 결과로 나온 행렬데이터에서 평균값을 출력하고 평균값보다 큰 숫자들만 유니크한 리스트로 나열하세요 (평균값은 소수 둘째 자리까지만 나타내세요) - ok

In [12]:
avg_data2 = np.round(data2.mean(), decimals=2)
print("avg : ", avg_data2)

data3 = np.unique(data2[data2>avg_data2])
data3


avg :  8.33


array([ 9, 10, 14, 18])

##### 12. 1부터 20까지의 랜덤숫자를 가지는 5*5 행렬을 만드시고 최대값에는 숫자(MAX), 최소값에는 숫자(MIN)으로 행렬을 바꾸세요 - ok

In [15]:
np.random.seed(2) #fixed random number generate 
data = np.random.randint(1,21,(5,5))
print(data)
print()

data1 = data.flatten()

min_data = data1.min()
max_data = data1.max()

print("min :", min_data, "\nmax :", max_data)


data1 = data1.astype('U21')

data1[min_data] = "{}({})".format(min_data, "min")
data1[max_data] = "{}({})".format(max_data, "max")

data2 = data1.reshape(5,5)
data2

[[ 9 16 14  9 12]
 [19 12  9  8  3]
 [18 12 16  6  8]
 [ 4  7  5 11 12]
 [20  8  7 11  2]]

min : 2 
max : 20


array([['9', '16', '2(min)', '9', '12'],
       ['19', '12', '9', '8', '3'],
       ['18', '12', '16', '6', '8'],
       ['4', '7', '5', '11', '12'],
       ['20(max)', '8', '7', '11', '2']], dtype='<U21')

##### 13. 100에서 130까지의 랜덤 숫자를 가지는 8*8행렬을 만드시고 3의 배수에는 fiz, 5의 배수에는 buz, 3과 5의 배수는 fbz 문자를 출력하세요 - ok

In [129]:
np.random.seed(3) #fixed random number generate 
data = np.random.randint(100,131,(8,8), dtype = int)
print(data)
print()

data1 = data.flatten()

ls = []
for idx in data1:
    if idx % 3 ==0 and idx % 5 ==0:
        idx = "fzb"
    elif idx % 3 == 0:
        idx = "fizz"
    elif idx % 5 == 0:
        idx = "buzz"
    else:
        idx
        
    ls.append(idx)
    

ls = np.stack(ls)
ls = ls.reshape(8,8)
ls

[[110 124 125 103 124 108 100 121]
 [129 119 110 111 125 109 110 121]
 [123 106 100 120 112 129 107 114]
 [124 126 117 126 122 102 102 128]
 [101 119 126 105 108 114 101 129]
 [110 124 127 130 107 124 111 101]
 [127 115 116 105 120 130 117 121]
 [114 120 128 123 122 100 100 109]]



array([['buzz', '124', 'buzz', '103', '124', 'fizz', 'buzz', '121'],
       ['fizz', '119', 'buzz', 'fizz', 'buzz', '109', 'buzz', '121'],
       ['fizz', '106', 'buzz', 'fzb', '112', 'fizz', '107', 'fizz'],
       ['124', 'fizz', 'fizz', 'fizz', '122', 'fizz', 'fizz', '128'],
       ['101', '119', 'fizz', 'fzb', 'fizz', 'fizz', '101', 'fizz'],
       ['buzz', '124', '127', 'buzz', '107', '124', 'fizz', '101'],
       ['127', 'buzz', '116', 'fzb', 'fzb', 'buzz', 'fizz', '121'],
       ['fizz', 'fzb', '128', 'fizz', '122', 'buzz', 'buzz', '109']],
      dtype='<U21')

##### 14. 리스트 컴프리헨션을 이용하여 아래와 같은 규칙은 갖는 행렬을 만드세요 - ok

In [110]:
# numbers = 5

# data1 = np.arange(1, numbers+1)*1
# data2 = np.arange(1, numbers+1)*2
# data3 = np.arange(1, numbers+1)*3
# data4 = np.arange(1, numbers+1)*4
# data5 = np.arange(1, numbers+1)*5

# data_sum = np.vstack((data1, data2, data3, data4, data5))
# data_sum

In [111]:
numbers = int(input("numbers : "))

ls = [np.arange(1, numbers+1)*idx  for idx in range(1, numbers+1)]
data = np.stack(ls)
data

numbers : 5


array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [102]:
numbers = 5
ls = []
for idx in range(1, numbers +1):
    data = np.arange(1, numbers+1)*idx
    ls.append(data)

# data_sum = np.stack((ls[0], ls[1], ls[2], ls[3], ls[4]))
# print(data_sum)

data_ = np.stack(ls)
data_
# for num in range(1,numbers):
#     print(num)
#     data_sum = np.stack((ls[0]))

#     data_sum2 = np.stack((data_sum,ls[num]))

# data_sum2

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])