### Quiz

In [2]:
import numpy as np

##### 1. 5개의 1로 이루어진 정수데이터 타입의 벡터를 만드세요

In [3]:
data = np.zeros(5, dtype = int)
data

array([0, 0, 0, 0, 0])

##### 2. 10개의 1로 이루어진 정수 데이터 타입의 벡터에서 마지막 3개의 데이터는 5가 들어있는 벡터를 만드세요

array([1, 1, 1, 1, 1, 1, 1, 5, 5, 5])

##### 3. 10에서 20까지의 데이터를 가지는 벡터를 만드세요

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

##### 4. 위 벡터의 순서를 바꾸세요

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

##### 5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### 6. 위의 벡터에서  `[[4,5],[7,8]]`  행렬을 만드세요

array([[4, 5],
       [7, 8]])

##### 7. 1에서 10까지의 데이터를 랜덤하게 가지는 3*4 행렬을 만드세요

array([[2, 2, 2, 8],
       [9, 6, 2, 5],
       [6, 1, 2, 1]])

##### 8. 위에서 만든 행렬의 unique 한 숫자들 리스트와 각숫자의 갯수를 리스트로 나타내세요

(array([1, 2, 5, 6, 8, 9]), array([2, 5, 1, 2, 1, 1]))

##### 9. 1에서 12까지에 숫자가 들어간 3*4 행렬을 만드시고 행과 열에 관계없이 데이터를 섞으세요

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

array([[ 5,  2, 10,  8],
       [ 7, 11,  9, 12],
       [ 1,  3,  6,  4]])

##### 10. 1부터 10까지의 랜덤한 데이터가 들어가는 `3*3`행렬을 만드시고 가장 아래에 위의 데이터를 모두 합한 `1*3`행렬을 추가해서 `4*3`행렬을 만드세요

array([[1, 3, 7],
       [5, 2, 7],
       [2, 4, 7]])

array([[ 1,  3,  7],
       [ 5,  2,  7],
       [ 2,  4,  7],
       [ 8,  9, 21]])

##### 11. 10번문제의 결과로 나온 행렬데이터에서 평균값을 출력하고 평균값보다 큰 숫자들만 유니크한 리스트로 나열하세요 (평균값은 소수 둘째 자리까지만 나타내세요)

avg :  6.33


array([ 7,  8,  9, 21])

##### 12. 1부터 20까지의 랜덤숫자를 가지는 5*5 행렬을 만드시고 최대값에는 숫자(MAX), 최소값에는 숫자(MIN)으로 행렬을 바꾸세요

array([[16, 20,  5,  3, 16],
       [13,  4, 15,  2,  5],
       [ 7, 19,  6,  5, 19],
       [19, 14, 13,  2,  4],
       [ 9,  8,  5, 19,  4]])

array([['16', '20(MAX)', '5', '3', '16'],
       ['13', '4', '15', '2(MIN)', '5'],
       ['7', '19', '6', '5', '19'],
       ['19', '14', '13', '2(MIN)', '4'],
       ['9', '8', '5', '19', '4']], dtype='<U21')

##### 13. 100에서 130까지의 랜덤 숫자를 가지는 8*8행렬을 만드시고 3의 배수에는 fiz, 5의 배수에는 buz, 3과 5의 배수는 fbz 문자를 출력하세요

array([[115, 115, 129, 116, 106],
       [128, 107, 102, 110, 122],
       [110, 124, 118, 126, 116],
       [105, 110, 105, 111, 119],
       [121, 113, 121, 117, 118]])

array([['buz', 'buz', 'fiz', '116', '106'],
       ['128', '107', 'fiz', 'buz', '122'],
       ['buz', '124', '118', 'fiz', '116'],
       ['fbz', 'buz', 'fbz', 'fiz', '119'],
       ['121', '113', '121', 'fiz', '118']], dtype='<U21')

##### 14. 리스트 컴프리헨션을 이용하여 아래와 같은 규칙은 갖는 행렬을 만드세요

number :  5


array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

number :  7


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 2,  4,  6,  8, 10, 12, 14],
       [ 3,  6,  9, 12, 15, 18, 21],
       [ 4,  8, 12, 16, 20, 24, 28],
       [ 5, 10, 15, 20, 25, 30, 35],
       [ 6, 12, 18, 24, 30, 36, 42],
       [ 7, 14, 21, 28, 35, 42, 49]])